pipeline {
  agent any
  stages {
    stage('Build Backend') {
      steps {
        sh 'cd backend && ./mvnw clean package'
      }
    }
    stage('Build Frontend') {
      steps {
        sh 'cd frontend/react-ui && npm install && npm run build'
      }
    }
    stage('Docker Build') {
      steps {
        sh 'docker-compose -f deployment/docker-compose.yml up -d --build'
      }
    }
  }
}